### ISSUE TITLE
rapp-platform status

### ISSUE THREAD

**Issue by shaun-edwards** [robotics-4-all/rapp-platform#1]
I noticed that this org has some of the latest commits to the `rapp-platform`.  Do you intend to "maintain" this package for open source users or just yourselves?

**Comment by etsardou** [comment]
Hello Shawn, unfortunately the "official" ```rapp-platform``` repository has been abandoned. We were the primary developers of it, thus we forked it here to clean it up and add extra features that serve our needs. Of course any work to be done concerning the ```rapp-platform``` will be open source.

**Comment by shaun-edwards** [comment]
Thanks for the reply.  We are in a similar situation.  We are just using the email sending functionality for now.  We've open sourced our changes (nothing material) as well, [here](https://github.com/plusone-robotics/rapp-platform).
